### ISSUE TITLE
Crash on get UUID on some Linux distro's

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_smart-device#182]
sankethbk7777 contact me in discord about a bug while running the code for the first time.
He runs it on Manjaro Linux distro 

```dart
Board type does not exist
This device is of type: null

Unhandled exception:
RangeError (start): Invalid value: Only valid value is 0: -1
#0      RangeError.checkValidRange (dart:core/errors.dart:358:7)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
#2      CommonBashCommandsD.getUuidOfCurrentDevice (package:cbj_smart_device/infrastructure/datasources/system_commands_d/bash_commands_d/common_bash_commands_d.dart:43:21)
<asynchronous suspension>
#3      LocalDbR.getListOfSmartDevices (package:cbj_smart_device/infrastructure/repositories/local_db_r/local_db_r.dart:24:38)
<asynchronous suspension>
#4      LocalDbE.getListOfSmartDevices (package:cbj_smart_device/domain/entities/local_db_e/local_db_e.dart:14:9)
<asynchronous suspension>
#5      SmartDeviceManagerU.smartDeviceMainAsync (package:cbj_smart_device/application/usecases/core_u/smart_device_manager_u.dart:26:9)
<asynchronous suspension>

```

**Comment by guyluz11** [comment]
Waiting for a response from the person that reported it in order to close this issue.
