### ISSUE TITLE
Running smart device on windows fail

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Smart-Device#28]
The program exits with the following error:

```dart

Smart device is activated
Path/argument 1 is not specified
error: RangeError (index): Invalid value: Valid value range is empty: 0
Unhandled exception:
RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      CommonBashCommendsD.getDeviceHostName (package:SmartDeviceDart/features/smart_device/infrastructure/datasources/bash_commends_d/common_bash_commends_d.dart:45:21)
<asynchronous suspension>
#2      DevicePinListManager.setPhysicalDeviceTypeByHostName (package:SmartDeviceDart/features/smart_device/infrastructure/datasources/core_d/manage_physical_components/device_pin_manager.dart:39:52)
#3      main (file:///C:/Users/The%20Vegan/Desktop/tets%20for%20guy/CBJ_Smart-Device/SmartDeviceDart/bin/main.dart:18:32)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Process finished with exit code 255

```

**Comment by guyluz11** [comment]
Smart device was built for Linux device and was not tested on windows.

The error crash trying to run Linux bash commands, we need to implement the windows version of this file and make the software run the correct one depending on the os that the software detects.

Importing `import 'dart:io';` will grant you detecting the os:

```
Platform.isLinux;
Platform.isWindows;
Platform.isMacOS;`

```

**Comment by guyluz11** [comment]
Fixed  

Thanks for reporting.
